language: csharp
solution: OctaneDownloadEngine.sln
mono: none
dotnet: 3.0.100
install:
 - sudo apt-get install nunit-console
script:
 - dotnet restore
 - dotnet build ./OctaneDownloadEngine.sln
 - nunit-console ./OctaneEngine/bin/Debug/OctaneEngine.dll
