name: Publish NuGet package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: actions/cache@v2
        id: cacheStep
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore dependencies
        run: dotnet restore
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore NuGet
        if: steps.cacheStep.outputs.cache-hit != 'true'
          run: nuget restore Octane.sln
      - name: Build and pack
        run: dotnet build -c Release && dotnet pack -c Release -o ./nupkg
      - name: Publish NuGet package
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_AUTH_TOKEN }}
          nuget-version: ${{ github.ref }}
          nuget-packages-folder: './nupkg'
